### ISSUE TITLE
Add Documentation to repository

### ISSUE THREAD

**Issue by brunocastroibarburu94** [JuDO-dev/AirBorne.jl#2]
**As a:** Project collaborator
**I want:** To have a centralized documentation page
**So that:** I can gain and provide context on the inner workings of the package

**Comment by imciner2** [comment]
Ok, the repository is public now and I have enabled github pages using the `gh-pages` branch as its source. The documentation can now be viewed online: https://judo.dev/AirBorne.jl/dev/.

**Comment by brunocastroibarburu94** [comment]
@imciner2 @LucianNita  Thank you very much Ian and Lucian, the repo is looking good!
